services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      PYTHONUNBUFFERED: 1
    volumes:
      - ./backend:/app
      - ./logs:/logs

  mongo:
    image: mongo:6.0
    container_name: streamline-mongo
    command: ["mongod", "--quiet", "--logpath", "/dev/null", "--logappend"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data: